Repository project-cybersyn-game/project-cybersyn-game, pull requests merged in 2022-02, with the labels that each got.

#64 58 refactor gamescence classes
  src/components/GameScene.ts
  src/components/GlobalGameState.ts
  src/scenes/CorfoIndoorScene.ts
  src/scenes/EntelBasementScene.ts
  src/scenes/EntelIndoorScene.ts
  src/scenes/MainMenuScene.ts
  src/scenes/OutdoorScene.ts
Labels: enhancement

#70 67 interaction performance
  src/components/GameScene.ts
  src/helpers/Characters.ts
  src/helpers/NpcsAndObjects.ts
  src/index.html
  src/main.ts
  src/scenes/CorfoIndoorScene.ts
  src/scenes/EntelBasementScene.ts
  src/scenes/EntelIndoorScene.ts
  src/scenes/OutdoorScene.ts
Labels: bug

#72 doors are now part of Npcsandobjects
  src/components/GameScene.ts
  src/helpers/Characters.ts
  src/helpers/Doors.ts
  src/helpers/NpcsAndObjects.ts
  src/scenes/CorfoIndoorScene.ts
  src/scenes/EntelBasementScene.ts
  src/scenes/EntelIndoorScene.ts
  src/scenes/OutdoorScene.ts
  static/images/door.png
  static/images/emptyDoorGraphic.png
  static/images/soil-negativ.png
Labels: enhancement

#74 Animate text & Added blinking Choice selector
  src/helpers/DialogueWindow.ts
  src/scenes/DialogueScene.ts
Labels: bug, enhancement
